//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/junit/build_result/java/junit/framework/AssertionFailedError.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/lang/AssertionError.h"

#define JunitFrameworkAssertionFailedError_serialVersionUID 1

@interface JunitFrameworkAssertionFailedError : JavaLangAssertionError {
}

- (id)init;
- (id)initWithNSString:(NSString *)message;
+ (NSString *)defaultStringWithNSString:(NSString *)message;
@end
