//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/junit/build_result/java/junit/framework/Protectable.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"

@protocol JunitFrameworkProtectable < NSObject >
- (void)protect;
@end
