//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/junit/build_result/java/junit/framework/Test.java
//
//  Created by tball on 2/19/13.
//

@class JunitFrameworkTestResult;

#import "JreEmulation.h"

@protocol JunitFrameworkTest < NSObject >
- (int)countTestCases;
- (void)runWithJunitFrameworkTestResult:(JunitFrameworkTestResult *)result;
@end
