//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/annotation/src/main/java/java/lang/annotation/Annotation.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"

@protocol JavaLangAnnotationAnnotation < NSObject >
- (IOSClass *)annotationType;
- (BOOL)isEqual:(id)obj;
- (NSUInteger)hash;
- (NSString *)description;
@end
