//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/org/apache/harmony/luni/platform/Endianness.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"

@interface OrgApacheHarmonyLuniPlatformEndianness : NSObject {
 @public
  NSString *displayName_;
}

@property (nonatomic, copy) NSString *displayName;

+ (OrgApacheHarmonyLuniPlatformEndianness *)getBIG_ENDIAN;
+ (OrgApacheHarmonyLuniPlatformEndianness *)getLITTLE_ENDIAN;
- (id)initWithNSString:(NSString *)displayName;
- (NSString *)description;
@end
