//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/io/ByteArrayOutputStream.java
//
//  Created by tball on 2/19/13.
//

@class IOSByteArray;

#import "JreEmulation.h"
#import "java/io/OutputStream.h"

@interface JavaIoByteArrayOutputStream : JavaIoOutputStream {
 @public
  IOSByteArray *buf_;
  int count_;
}

@property (nonatomic, retain) IOSByteArray *buf;
@property (nonatomic, assign) int count;

- (id)init;
- (id)initWithInt:(int)size;
- (void)close;
- (void)expandWithInt:(int)i;
- (void)reset;
- (int)size;
- (IOSByteArray *)toByteArray;
- (NSString *)description;
- (NSString *)toStringWithInt:(int)hibyte;
- (NSString *)toStringWithNSString:(NSString *)enc;
- (void)writeWithJavaLangByteArray:(IOSByteArray *)buffer
                           withInt:(int)offset
                           withInt:(int)len;
- (void)writeWithInt:(int)oneByte;
- (void)writeToWithJavaIoOutputStream:(JavaIoOutputStream *)outArg;
@end
