//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/io/SyncFailedException.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/io/IOException.h"

#define JavaIoSyncFailedException_serialVersionUID -2353342684412443330

@interface JavaIoSyncFailedException : JavaIoIOException {
}

- (id)initWithNSString:(NSString *)detailMessage;
@end
