//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/util/Queue.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/util/Collection.h"

@protocol JavaUtilQueue < JavaUtilCollection, NSObject >
- (BOOL)offerWithId:(id)o;
- (id)poll;
- (id)remove;
- (id)peek;
- (id)element;
@end
