//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/util/RandomAccess.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"

@protocol JavaUtilRandomAccess < NSObject >
@end
