//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/android/libcore/luni/src/main/java/java/util/StringTokenizer.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/util/Enumeration.h"

@interface JavaUtilStringTokenizer : NSObject < JavaUtilEnumeration > {
 @public
  NSString *string_;
  NSString *delimiters_;
  BOOL returnDelimiters_;
  int position_;
}

@property (nonatomic, copy) NSString *string;
@property (nonatomic, copy) NSString *delimiters;
@property (nonatomic, assign) BOOL returnDelimiters;
@property (nonatomic, assign) int position;

- (id)initWithNSString:(NSString *)string;
- (id)initWithNSString:(NSString *)string
          withNSString:(NSString *)delimiters;
- (id)initWithNSString:(NSString *)string
          withNSString:(NSString *)delimiters
              withBOOL:(BOOL)returnDelimiters;
- (int)countTokens;
- (BOOL)hasMoreElements;
- (BOOL)hasMoreTokens;
- (id)nextElement;
- (NSString *)nextToken;
- (NSString *)nextTokenWithNSString:(NSString *)delims;
@end
