//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/nio/src/main/java/common/java/nio/BufferUnderflowException.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/lang/RuntimeException.h"

#define JavaNioBufferUnderflowException_serialVersionUID -1713313658691622206

@interface JavaNioBufferUnderflowException : JavaLangRuntimeException {
}

- (id)init;
@end
