//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/nio/src/main/java/common/java/nio/ByteOrder.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"

@interface JavaNioByteOrder : NSObject {
 @public
  NSString *name_;
}

@property (nonatomic, copy) NSString *name;

+ (JavaNioByteOrder *)getBIG_ENDIAN;
+ (JavaNioByteOrder *)getLITTLE_ENDIAN;
+ (JavaNioByteOrder *)NATIVE_ORDER;
+ (BOOL)isLittleEndian;
+ (JavaNioByteOrder *)nativeOrder;
- (id)initWithNSString:(NSString *)name;
- (NSString *)description;
@end
