//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/nio/src/main/java/common/java/nio/ReadOnlyBufferException.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/lang/UnsupportedOperationException.h"

#define JavaNioReadOnlyBufferException_serialVersionUID -1210063976496234090

@interface JavaNioReadOnlyBufferException : JavaLangUnsupportedOperationException {
}

- (id)init;
@end
