//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/Classes/java/util/logging/NSLogHandler.java
//
//  Created by tball on 2/19/13.
//

@class JavaUtilLoggingLogRecord;

#import "JreEmulation.h"
#import "java/util/logging/Formatter.h"
#import "java/util/logging/Handler.h"

@interface JavaUtilLoggingNSLogHandler : JavaUtilLoggingHandler {
}

- (id)init;
- (void)close;
- (void)flush;
- (void)publishWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;
- (void)logWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;
@end

@interface JavaUtilLoggingNSLogHandler_NSLogFormatter : JavaUtilLoggingFormatter {
}

- (NSString *)formatWithJavaUtilLoggingLogRecord:(JavaUtilLoggingLogRecord *)record;
@end
