//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/Appendable.java
//
//  Created by tball on 2/19/13.
//

@protocol JavaLangCharSequence;

#import "JreEmulation.h"

@protocol JavaLangAppendable < NSObject >
- (id<JavaLangAppendable>)appendWithUnichar:(unichar)c;
- (id<JavaLangAppendable>)appendWithJavaLangCharSequence:(id<JavaLangCharSequence>)csq;
- (id<JavaLangAppendable>)appendWithJavaLangCharSequence:(id<JavaLangCharSequence>)csq
                                                 withInt:(int)start
                                                 withInt:(int)end;
@end
