//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/AssertionError.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/lang/Error.h"

#define JavaLangAssertionError_serialVersionUID -5013299493970297370

@interface JavaLangAssertionError : JavaLangError {
}

- (id)init;
- (id)initWithId:(id)detailMessage;
- (id)initWithBOOL:(BOOL)detailMessage;
- (id)initWithUnichar:(unichar)detailMessage;
- (id)initWithInt:(int)detailMessage;
- (id)initWithLongInt:(long long int)detailMessage;
- (id)initWithFloat:(float)detailMessage;
- (id)initWithDouble:(double)detailMessage;
@end
