//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/IllegalThreadStateException.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/lang/IllegalArgumentException.h"

#define JavaLangIllegalThreadStateException_serialVersionUID -7626246362397460174

@interface JavaLangIllegalThreadStateException : JavaLangIllegalArgumentException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
