//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/LinkageError.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/lang/Error.h"

#define JavaLangLinkageError_serialVersionUID 3579600108157160122

@interface JavaLangLinkageError : JavaLangError {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
