//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/NoSuchFieldException.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/lang/Exception.h"

#define JavaLangNoSuchFieldException_serialVersionUID -6143714805279938260

@interface JavaLangNoSuchFieldException : JavaLangException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
