//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/NoSuchMethodException.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/lang/Exception.h"

#define JavaLangNoSuchMethodException_serialVersionUID 5034388446362600923

@interface JavaLangNoSuchMethodException : JavaLangException {
}

- (id)init;
- (id)initWithNSString:(NSString *)detailMessage;
@end
