//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/StringIndexOutOfBoundsException.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/lang/IndexOutOfBoundsException.h"

#define JavaLangStringIndexOutOfBoundsException_serialVersionUID -6762910422159637258

@interface JavaLangStringIndexOutOfBoundsException : JavaLangIndexOutOfBoundsException {
}

- (id)init;
- (id)initWithInt:(int)index;
- (id)initWithNSString:(NSString *)detailMessage;
@end
