//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/Classes/java/lang/ThreadLocal.java
//
//  Created by tball on 2/19/13.
//

@class JavaUtilConcurrentAtomicAtomicInteger;

#import "JreEmulation.h"

@interface JavaLangThreadLocal : NSObject {
 @public
  NSString *key_;
}

@property (nonatomic, copy) NSString *key;

+ (NSString *)KEY_PREFIX;
+ (JavaUtilConcurrentAtomicAtomicInteger *)nextId;
- (id)get;
- (id)initialValue OBJC_METHOD_FAMILY_NONE;
- (void)remove;
- (void)setWithId:(id)value;
- (id)getNative;
- (void)removeNative;
- (void)setNativeWithId:(id)value;
- (id)init;
@end
