//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/ThreadDeath.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"
#import "java/lang/Error.h"

#define JavaLangThreadDeath_serialVersionUID -4417128565033088268

@interface JavaLangThreadDeath : JavaLangError {
}

- (id)init;
@end
