//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/android/libcore/luni/src/main/java/java/util/regex/MatchResult.java
//
//  Created by tball on 2/19/13.
//

#import "JreEmulation.h"

@protocol JavaUtilRegexMatchResult < NSObject >
- (int)end;
- (int)endWithInt:(int)group;
- (NSString *)group;
- (NSString *)groupWithInt:(int)group;
- (int)groupCount;
- (int)start;
- (int)startWithInt:(int)group;
@end
