//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/android/libcore/luni/src/main/java/java/util/regex/MatchResultImpl.java
//
//  Created by tball on 2/19/13.
//

@class IOSIntArray;

#import "JreEmulation.h"
#import "java/util/regex/MatchResult.h"

@interface JavaUtilRegexMatchResultImpl : NSObject < JavaUtilRegexMatchResult > {
 @public
  NSString *text_;
  IOSIntArray *offsets_;
}

@property (nonatomic, copy) NSString *text;
@property (nonatomic, retain) IOSIntArray *offsets;

- (id)initWithNSString:(NSString *)text
withJavaLangIntegerArray:(IOSIntArray *)offsets;
- (int)end;
- (int)endWithInt:(int)group;
- (NSString *)group;
- (NSString *)groupWithInt:(int)group;
- (int)groupCount;
- (int)start;
- (int)startWithInt:(int)group;
@end
