//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/reflect/GenericDeclaration.java
//
//  Created by tball on 2/19/13.
//

@class IOSObjectArray;

#import "JreEmulation.h"

@protocol JavaLangReflectGenericDeclaration < NSObject >
- (IOSObjectArray *)getTypeParameters;
@end
