//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/reflect/InvocationTargetException.java
//
//  Created by tball on 2/19/13.
//

@class JavaLangThrowable;

#import "JreEmulation.h"
#import "java/lang/Exception.h"

#define JavaLangReflectInvocationTargetException_serialVersionUID 4085088731926701167

@interface JavaLangReflectInvocationTargetException : JavaLangException {
 @public
  JavaLangThrowable *target_;
}

@property (nonatomic, retain) JavaLangThrowable *target;

- (id)init;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)exception;
- (id)initWithJavaLangThrowable:(JavaLangThrowable *)exception
                   withNSString:(NSString *)detailMessage;
- (JavaLangThrowable *)getTargetException;
- (JavaLangThrowable *)getCause;
@end
