//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/apache_harmony/classlib/modules/luni/src/main/java/java/lang/reflect/TypeVariable.java
//
//  Created by tball on 2/19/13.
//

@class IOSObjectArray;
@protocol JavaLangReflectGenericDeclaration;

#import "JreEmulation.h"
#import "java/lang/reflect/Type.h"

@protocol JavaLangReflectTypeVariable < JavaLangReflectType, NSObject >
- (IOSObjectArray *)getBounds;
- (id)getGenericDeclaration;
- (NSString *)getName;
@end
