//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/Classes/java/util/concurrent/Executor.java
//
//  Created by tball on 2/19/13.
//

@protocol JavaLangRunnable;

#import "JreEmulation.h"

@protocol JavaUtilConcurrentExecutor < NSObject >
- (void)executeWithJavaLangRunnable:(id<JavaLangRunnable>)command;
@end
