//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/tball/tmp/j2objc-0.6.1/jre_emul/Classes/java/util/concurrent/Future.java
//
//  Created by tball on 2/19/13.
//

@class JavaUtilConcurrentTimeUnitEnum;

#import "JreEmulation.h"

@protocol JavaUtilConcurrentFuture < NSObject >
- (BOOL)cancelWithBOOL:(BOOL)mayInterruptIfRunning;
- (BOOL)isCancelled;
- (BOOL)isDone;
- (id)get;
- (id)getWithLongInt:(long long int)timeout
withJavaUtilConcurrentTimeUnitEnum:(JavaUtilConcurrentTimeUnitEnum *)unit;
@end
